apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-component
    app.kubernetes.io/part-of: ubi-image-builder
  name: my-component
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: my-component
status:
  loadBalancer: {}
